displayName: hello plugin
type: middleware

import: github.com/intaacopilot/hellotest

summary: '[hello] A message returner.'

testData:
  message: "I will ask you to write another 10 points there."
  statusCode: 200
  headers:
    Content-Type: "text/plain"
